{"topicSections":[{"title":"Classes","identifiers":["doc:\/\/com.olamap.core.OlaMapCore\/documentation\/OlaMapCore\/CabAnnotationView","doc:\/\/com.olamap.core.OlaMapCore\/documentation\/OlaMapCore\/MapRouteHelper","doc:\/\/com.olamap.core.OlaMapCore\/documentation\/OlaMapCore\/MapUtility","doc:\/\/com.olamap.core.OlaMapCore\/documentation\/OlaMapCore\/OLATrafficModel","doc:\/\/com.olamap.core.OlaMapCore\/documentation\/OlaMapCore\/OlaAnnotationView","doc:\/\/com.olamap.core.OlaMapCore\/documentation\/OlaMapCore\/OlaDistanceFormatter","doc:\/\/com.olamap.core.OlaMapCore\/documentation\/OlaMapCore\/OlaMapInstrumentation","doc:\/\/com.olamap.core.OlaMapCore\/documentation\/OlaMapCore\/OlaMapMarker","doc:\/\/com.olamap.core.OlaMapCore\/documentation\/OlaMapCore\/OlaMapService","doc:\/\/com.olamap.core.OlaMapCore\/documentation\/OlaMapCore\/OlaStepRoute"]},{"title":"Protocols","identifiers":["doc:\/\/com.olamap.core.OlaMapCore\/documentation\/OlaMapCore\/MapInstrumentationProtocol","doc:\/\/com.olamap.core.OlaMapCore\/documentation\/OlaMapCore\/MapServiceProtocol","doc:\/\/com.olamap.core.OlaMapCore\/documentation\/OlaMapCore\/OlaMapInstrumentationDelegate","doc:\/\/com.olamap.core.OlaMapCore\/documentation\/OlaMapCore\/OlaMapServiceDelegate"]},{"identifiers":["doc:\/\/com.olamap.core.OlaMapCore\/documentation\/OlaMapCore\/OlaCoordinate","doc:\/\/com.olamap.core.OlaMapCore\/documentation\/OlaMapCore\/POIModel"],"title":"Structures"},{"identifiers":["doc:\/\/com.olamap.core.OlaMapCore\/documentation\/OlaMapCore\/AuthType","doc:\/\/com.olamap.core.OlaMapCore\/documentation\/OlaMapCore\/NavigationTrackingMode","doc:\/\/com.olamap.core.OlaMapCore\/documentation\/OlaMapCore\/OlaMapError","doc:\/\/com.olamap.core.OlaMapCore\/documentation\/OlaMapCore\/OlaMapGesture","doc:\/\/com.olamap.core.OlaMapCore\/documentation\/OlaMapCore\/OlaTrafficType","doc:\/\/com.olamap.core.OlaMapCore\/documentation\/OlaMapCore\/PolylineType"],"title":"Enumerations"},{"title":"Extended Modules","identifiers":["doc:\/\/com.olamap.core.OlaMapCore\/documentation\/OlaMapCore\/CoreLocation","doc:\/\/com.olamap.core.OlaMapCore\/documentation\/OlaMapCore\/Foundation"]}],"kind":"symbol","sections":[],"metadata":{"modules":[{"name":"OlaMapCore"}],"roleHeading":"Framework","title":"OlaMapCore","externalID":"OlaMapCore","symbolKind":"module","role":"collection"},"hierarchy":{"paths":[[]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.olamap.core.OlaMapCore\/documentation\/OlaMapCore"},"schemaVersion":{"patch":0,"major":0,"minor":3},"primaryContentSections":[{"content":[{"text":"Overview","type":"heading","level":2,"anchor":"Overview"}],"kind":"content"}],"variants":[{"paths":["\/documentation\/olamapcore"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/olamapcore"]}],"references":{"doc://com.olamap.core.OlaMapCore/documentation/OlaMapCore/OLATrafficModel":{"role":"symbol","identifier":"doc:\/\/com.olamap.core.OlaMapCore\/documentation\/OlaMapCore\/OLATrafficModel","navigatorTitle":[{"kind":"identifier","text":"OLATrafficModel"}],"url":"\/documentation\/olamapcore\/olatrafficmodel","title":"OLATrafficModel","type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"OLATrafficModel"}],"abstract":[{"text":"Model to render traffic poyline.","type":"text"}]},"doc://com.olamap.core.OlaMapCore/documentation/OlaMapCore":{"abstract":[],"url":"\/documentation\/olamapcore","identifier":"doc:\/\/com.olamap.core.OlaMapCore\/documentation\/OlaMapCore","type":"topic","title":"OlaMapCore","role":"collection","kind":"symbol"},"doc://com.olamap.core.OlaMapCore/documentation/OlaMapCore/MapServiceProtocol":{"type":"topic","identifier":"doc:\/\/com.olamap.core.OlaMapCore\/documentation\/OlaMapCore\/MapServiceProtocol","kind":"symbol","abstract":[],"url":"\/documentation\/olamapcore\/mapserviceprotocol","navigatorTitle":[{"kind":"identifier","text":"MapServiceProtocol"}],"fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"MapServiceProtocol","kind":"identifier"}],"title":"MapServiceProtocol","role":"symbol"},"doc://com.olamap.core.OlaMapCore/documentation/OlaMapCore/OlaMapServiceDelegate":{"fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"OlaMapServiceDelegate"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"OlaMapServiceDelegate"}],"identifier":"doc:\/\/com.olamap.core.OlaMapCore\/documentation\/OlaMapCore\/OlaMapServiceDelegate","type":"topic","url":"\/documentation\/olamapcore\/olamapservicedelegate","abstract":[],"kind":"symbol","title":"OlaMapServiceDelegate"},"doc://com.olamap.core.OlaMapCore/documentation/OlaMapCore/OlaMapInstrumentationDelegate":{"navigatorTitle":[{"kind":"identifier","text":"OlaMapInstrumentationDelegate"}],"title":"OlaMapInstrumentationDelegate","kind":"symbol","identifier":"doc:\/\/com.olamap.core.OlaMapCore\/documentation\/OlaMapCore\/OlaMapInstrumentationDelegate","abstract":[],"type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"OlaMapInstrumentationDelegate"}],"url":"\/documentation\/olamapcore\/olamapinstrumentationdelegate"},"doc://com.olamap.core.OlaMapCore/documentation/OlaMapCore/OlaMapMarker":{"title":"OlaMapMarker","type":"topic","url":"\/documentation\/olamapcore\/olamapmarker","navigatorTitle":[{"text":"OlaMapMarker","kind":"identifier"}],"identifier":"doc:\/\/com.olamap.core.OlaMapCore\/documentation\/OlaMapCore\/OlaMapMarker","role":"symbol","abstract":[{"type":"text","text":"Map Marker which expects UIImage"}],"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"OlaMapMarker","kind":"identifier"}]},"doc://com.olamap.core.OlaMapCore/documentation/OlaMapCore/MapInstrumentationProtocol":{"type":"topic","title":"MapInstrumentationProtocol","url":"\/documentation\/olamapcore\/mapinstrumentationprotocol","identifier":"doc:\/\/com.olamap.core.OlaMapCore\/documentation\/OlaMapCore\/MapInstrumentationProtocol","abstract":[],"role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MapInstrumentationProtocol"}],"kind":"symbol","navigatorTitle":[{"text":"MapInstrumentationProtocol","kind":"identifier"}]},"doc://com.olamap.core.OlaMapCore/documentation/OlaMapCore/Foundation":{"url":"\/documentation\/olamapcore\/foundation","abstract":[],"role":"collection","kind":"symbol","title":"Foundation","type":"topic","identifier":"doc:\/\/com.olamap.core.OlaMapCore\/documentation\/OlaMapCore\/Foundation"},"doc://com.olamap.core.OlaMapCore/documentation/OlaMapCore/OlaMapGesture":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"OlaMapGesture"}],"type":"topic","identifier":"doc:\/\/com.olamap.core.OlaMapCore\/documentation\/OlaMapCore\/OlaMapGesture","abstract":[],"navigatorTitle":[{"text":"OlaMapGesture","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/olamapcore\/olamapgesture","role":"symbol","title":"OlaMapGesture"},"doc://com.olamap.core.OlaMapCore/documentation/OlaMapCore/OlaCoordinate":{"title":"OlaCoordinate","type":"topic","navigatorTitle":[{"kind":"identifier","text":"OlaCoordinate"}],"role":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"OlaCoordinate","kind":"identifier"}],"abstract":[],"kind":"symbol","identifier":"doc:\/\/com.olamap.core.OlaMapCore\/documentation\/OlaMapCore\/OlaCoordinate","url":"\/documentation\/olamapcore\/olacoordinate"},"doc://com.olamap.core.OlaMapCore/documentation/OlaMapCore/CoreLocation":{"role":"collection","identifier":"doc:\/\/com.olamap.core.OlaMapCore\/documentation\/OlaMapCore\/CoreLocation","url":"\/documentation\/olamapcore\/corelocation","title":"CoreLocation","type":"topic","kind":"symbol","abstract":[]},"doc://com.olamap.core.OlaMapCore/documentation/OlaMapCore/PolylineType":{"navigatorTitle":[{"kind":"identifier","text":"PolylineType"}],"identifier":"doc:\/\/com.olamap.core.OlaMapCore\/documentation\/OlaMapCore\/PolylineType","role":"symbol","kind":"symbol","url":"\/documentation\/olamapcore\/polylinetype","type":"topic","abstract":[],"title":"PolylineType","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"PolylineType"}]},"doc://com.olamap.core.OlaMapCore/documentation/OlaMapCore/OlaTrafficType":{"role":"symbol","url":"\/documentation\/olamapcore\/olatraffictype","kind":"symbol","abstract":[],"fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"OlaTrafficType","kind":"identifier"}],"title":"OlaTrafficType","navigatorTitle":[{"text":"OlaTrafficType","kind":"identifier"}],"identifier":"doc:\/\/com.olamap.core.OlaMapCore\/documentation\/OlaMapCore\/OlaTrafficType","type":"topic"},"doc://com.olamap.core.OlaMapCore/documentation/OlaMapCore/OlaMapCoreVersionNumber":{"role":"symbol","identifier":"doc:\/\/com.olamap.core.OlaMapCore\/documentation\/OlaMapCore\/OlaMapCoreVersionNumber","url":"\/documentation\/olamapcore\/olamapcoreversionnumber","title":"OlaMapCoreVersionNumber","type":"topic","kind":"symbol","fragments":[{"kind":"identifier","text":"OlaMapCoreVersionNumber"}],"abstract":[{"text":"Project version number for OlaMapCore.","type":"text"}]},"doc://com.olamap.core.OlaMapCore/documentation/OlaMapCore/CabAnnotationView":{"title":"CabAnnotationView","type":"topic","role":"symbol","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"CabAnnotationView"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CabAnnotationView","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/olamapcore\/cabannotationview","identifier":"doc:\/\/com.olamap.core.OlaMapCore\/documentation\/OlaMapCore\/CabAnnotationView"},"doc://com.olamap.core.OlaMapCore/documentation/OlaMapCore/OlaMapService":{"type":"topic","title":"OlaMapService","role":"symbol","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"OlaMapService"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"OlaMapService","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/olamapcore\/olamapservice","identifier":"doc:\/\/com.olamap.core.OlaMapCore\/documentation\/OlaMapCore\/OlaMapService"},"doc://com.olamap.core.OlaMapCore/documentation/OlaMapCore/MapRouteHelper":{"abstract":[],"identifier":"doc:\/\/com.olamap.core.OlaMapCore\/documentation\/OlaMapCore\/MapRouteHelper","type":"topic","url":"\/documentation\/olamapcore\/maproutehelper","title":"MapRouteHelper","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"MapRouteHelper","kind":"identifier"}],"navigatorTitle":[{"text":"MapRouteHelper","kind":"identifier"}],"kind":"symbol"},"doc://com.olamap.core.OlaMapCore/documentation/OlaMapCore/MapUtility":{"role":"symbol","kind":"symbol","navigatorTitle":[{"text":"MapUtility","kind":"identifier"}],"title":"MapUtility","url":"\/documentation\/olamapcore\/maputility","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"MapUtility","kind":"identifier"}],"abstract":[],"identifier":"doc:\/\/com.olamap.core.OlaMapCore\/documentation\/OlaMapCore\/MapUtility"},"doc://com.olamap.core.OlaMapCore/documentation/OlaMapCore/OlaStepRoute":{"kind":"symbol","abstract":[],"navigatorTitle":[{"text":"OlaStepRoute","kind":"identifier"}],"identifier":"doc:\/\/com.olamap.core.OlaMapCore\/documentation\/OlaMapCore\/OlaStepRoute","role":"symbol","title":"OlaStepRoute","url":"\/documentation\/olamapcore\/olasteproute","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"OlaStepRoute"}]},"doc://com.olamap.core.OlaMapCore/documentation/OlaMapCore/AuthType":{"identifier":"doc:\/\/com.olamap.core.OlaMapCore\/documentation\/OlaMapCore\/AuthType","url":"\/documentation\/olamapcore\/authtype","title":"AuthType","abstract":[],"type":"topic","role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"AuthType","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"AuthType"}]},"doc://com.olamap.core.OlaMapCore/documentation/OlaMapCore/OlaAnnotationView":{"kind":"symbol","url":"\/documentation\/olamapcore\/olaannotationview","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"OlaAnnotationView","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"OlaAnnotationView"}],"abstract":[],"title":"OlaAnnotationView","role":"symbol","identifier":"doc:\/\/com.olamap.core.OlaMapCore\/documentation\/OlaMapCore\/OlaAnnotationView"},"doc://com.olamap.core.OlaMapCore/documentation/OlaMapCore/NavigationTrackingMode":{"type":"topic","url":"\/documentation\/olamapcore\/navigationtrackingmode","role":"symbol","title":"NavigationTrackingMode","identifier":"doc:\/\/com.olamap.core.OlaMapCore\/documentation\/OlaMapCore\/NavigationTrackingMode","kind":"symbol","abstract":[],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NavigationTrackingMode","kind":"identifier"}],"navigatorTitle":[{"text":"NavigationTrackingMode","kind":"identifier"}]},"doc://com.olamap.core.OlaMapCore/documentation/OlaMapCore/POIModel":{"kind":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"kind":"identifier","text":"POIModel"}],"title":"POIModel","type":"topic","abstract":[],"identifier":"doc:\/\/com.olamap.core.OlaMapCore\/documentation\/OlaMapCore\/POIModel","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"POIModel"}],"url":"\/documentation\/olamapcore\/poimodel"},"doc://com.olamap.core.OlaMapCore/documentation/OlaMapCore/OlaMapError":{"role":"symbol","navigatorTitle":[{"text":"OlaMapError","kind":"identifier"}],"url":"\/documentation\/olamapcore\/olamaperror","type":"topic","identifier":"doc:\/\/com.olamap.core.OlaMapCore\/documentation\/OlaMapCore\/OlaMapError","kind":"symbol","abstract":[],"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"OlaMapError"}],"title":"OlaMapError"},"doc://com.olamap.core.OlaMapCore/documentation/OlaMapCore/OlaDistanceFormatter":{"navigatorTitle":[{"text":"OlaDistanceFormatter","kind":"identifier"}],"abstract":[],"role":"symbol","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"OlaDistanceFormatter","kind":"identifier"}],"title":"OlaDistanceFormatter","identifier":"doc:\/\/com.olamap.core.OlaMapCore\/documentation\/OlaMapCore\/OlaDistanceFormatter","url":"\/documentation\/olamapcore\/oladistanceformatter","type":"topic"},"doc://com.olamap.core.OlaMapCore/documentation/OlaMapCore/OlaMapInstrumentation":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"OlaMapInstrumentation"}],"url":"\/documentation\/olamapcore\/olamapinstrumentation","role":"symbol","abstract":[],"type":"topic","navigatorTitle":[{"text":"OlaMapInstrumentation","kind":"identifier"}],"kind":"symbol","title":"OlaMapInstrumentation","identifier":"doc:\/\/com.olamap.core.OlaMapCore\/documentation\/OlaMapCore\/OlaMapInstrumentation"},"doc://com.olamap.core.OlaMapCore/documentation/OlaMapCore/OlaMapCoreVersionString":{"kind":"symbol","title":"OlaMapCoreVersionString","url":"\/documentation\/olamapcore\/olamapcoreversionstring","abstract":[{"text":"Project version string for OlaMapCore.","type":"text"}],"type":"topic","role":"symbol","fragments":[{"text":"OlaMapCoreVersionString","kind":"identifier"}],"identifier":"doc:\/\/com.olamap.core.OlaMapCore\/documentation\/OlaMapCore\/OlaMapCoreVersionString"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/topicSections","value":[{"title":"Variables","identifiers":["doc:\/\/com.olamap.core.OlaMapCore\/documentation\/OlaMapCore\/OlaMapCoreVersionNumber","doc:\/\/com.olamap.core.OlaMapCore\/documentation\/OlaMapCore\/OlaMapCoreVersionString"]}]},{"op":"add","value":null,"path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"}]}]}